name: Update Blog Posts

on:
  workflow_dispatch:
  # Commented out since I don't regularly post on my blog
  # schedule:
  #   - cron: '0 0 * * 0' # runs once a week

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  update-blog-posts:
    name: Update Blog Posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Blog post workflow
        uses: gautamkrishnar/blog-post-workflow@1.9.6
        with:
          feed_list: "https://blog.lynkos.dev/feed.xml"
          max_post_count: 7
          commit_message: "Automatically updated blog posts in `README.md`"
          committer_username: "github-actions[bot]"
          committer_email: "github-actions[bot]@users.noreply.github.com"
