name: Update Stats GIF

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */2 * *' # runs at midnight every 2 days
  push:
    branches:
      - main
    paths:
      - main.py

env:
  GIF_NAME: output

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  update-stats-gif:
    name: Update Stats GIF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          lfs: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install github-readme-terminal
          echo "$GITHUB_WORKSPACE/.venv/bin" >> "$GITHUB_PATH"

      - name: Patch gifos to display Top 15 Languages
        run: |
          python - <<'PY'
          from pathlib import Path
          from re import sub
          from inspect import getfile
          from gifos.utils import fetch_github_stats

          p = Path(getfile(fetch_github_stats))
          text = p.read_text()
          new_text = sub(
              r"languages_sorted\s*=\s*languages_sorted\[[^\]]*\]\s*,?",
              "languages_sorted=languages_sorted[:15],",
              text,
              count = 1
          )
          
          if new_text != text: p.write_text(new_text)
          PY
      
      - name: Add Solarized theme
        run: |
          mkdir -p ~/.config/gifos
          cat > ~/.config/gifos/ansi_escape_colors.toml <<'EOF'
          [solarized]
                  [solarized.default_colors]
                  fg = "#839496"
                  bg = "#002b36"

                  [solarized.normal_colors]
                  black = "#073642"
                  red = "#dc322f"
                  green = "#859900"
                  yellow = "#b58900"
                  blue = "#268bd2"
                  magenta = "#d33682"
                  cyan = "#2aa198"
                  white = "#eee8d5"

                  [solarized.bright_colors]
                  black = "#002b36"
                  red = "#cb4b16"
                  green = "#859900"
                  yellow = "#b58900"
                  blue = "#268bd2"
                  magenta = "#6c71c4"
                  cyan = "#2aa198"
                  white = "#fdf6e3"
          EOF

      - name: Add gifos settings
        run: |
          mkdir -p ~/.config/gifos
          cat > ~/.config/gifos/gifos_settings.toml <<'EOF'
          [general]
          debug = false
          cursor = "_"
          show_cursor = true
          blink_cursor = true
          user_name = "lynkos"
          fps = 15
          color_scheme = "solarized"
          loop_count = 0

          [files]
          frame_base_name = "frame_"
          frame_folder_name = "frames"
          output_gif_name = "${GIF_NAME}"
          EOF

      - name: Generate GIF
        run: python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}

      - name: Upload GIF
        run: |
          git add "${GIF_NAME}.gif"
          git -c "user.name=github-actions[bot]" \
              -c "user.email=github-actions[bot]@users.noreply.github.com" \
              commit -m "Automatically updated stats gif (\`${GIF_NAME}.gif\`) on $(date)"
          git push